package org.javlo.client.localmodule.ui;

import java.awt.Dialog;

import javax.swing.JOptionPane;

import org.javlo.client.localmodule.model.ServerConfig;
import org.javlo.client.localmodule.service.ConfigService;
import org.javlo.client.localmodule.service.I18nService;
import org.javlo.helper.StringHelper;

/**
 *
 * @author lg2dc
 */
public class ServerFrame extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

	private static ServerFrame instance;

	public static void showDialog(ConfigFrame parent, ServerConfig server) {
		synchronized (ServerFrame.class) {
			if (instance == null) {
				instance = new ServerFrame();
				instance.loadConfig(parent, server);
				instance.setLocationRelativeTo(parent);
				instance.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
				instance.setVisible(true);
			} else {
				instance.toFront();
			}
		}
	}

	private I18nService i18n = I18nService.getInstance();

	private ServerConfig serverConfig;
	private ConfigFrame parent;

	public ServerFrame() {
		initComponents();
		getRootPane().setDefaultButton(btnOK);
	}

	public void close() {
		synchronized (ServerFrame.class) {
			this.setVisible(false);
			this.dispose();
			instance = null;
		}
	}

	private void loadConfig(ConfigFrame parent, ServerConfig server) {
		this.parent = parent;
		this.serverConfig = server;
		txtServerURL.setText(server.getServerURL());
	}

	private boolean saveConfig() {
		//Parse an check input values
		String serverURL = StringHelper.trimAndNullify(txtServerURL.getText());
		if (!ConfigService.checkServerURL(serverURL)) {
			JOptionPane.showMessageDialog(this, i18n.get("error.invalid-server-url"), i18n.get("error"), JOptionPane.ERROR_MESSAGE);
			txtServerURL.requestFocus();
			return false;
		}

		//Store
		serverConfig.setServerURL(serverURL);
		parent.onServerUpdate(serverConfig);
		return true;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnlLocal = new javax.swing.JPanel();
		txtServerURL = new javax.swing.JTextField();
		lblServerURL = new javax.swing.JLabel();
		pnlButton = new javax.swing.JPanel();
		btnOK = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle(i18n.get("config.server-title")); // NOI18N
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		lblServerURL.setText(i18n.get("config.server-url")); // NOI18N

		javax.swing.GroupLayout pnlLocalLayout = new javax.swing.GroupLayout(pnlLocal);
		pnlLocal.setLayout(pnlLocalLayout);
		pnlLocalLayout.setHorizontalGroup(
				pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlLocalLayout.createSequentialGroup()
								.addComponent(lblServerURL)
								.addGap(28, 28, 28)
								.addComponent(txtServerURL))
				);
		pnlLocalLayout.setVerticalGroup(
				pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblServerURL)
								.addComponent(txtServerURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);

		btnOK.setText(i18n.get("dialog.ok")); // NOI18N
		btnOK.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnOKActionPerformed(evt);
			}
		});

		btnCancel.setText(i18n.get("dialog.cancel")); // NOI18N
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
		pnlButton.setLayout(pnlButtonLayout);
		pnlButtonLayout.setHorizontalGroup(
				pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonLayout.createSequentialGroup()
								.addContainerGap(277, Short.MAX_VALUE)
								.addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
				);
		pnlButtonLayout.setVerticalGroup(
				pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlButtonLayout.createSequentialGroup()
								.addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(btnCancel)
										.addComponent(btnOK))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(pnlLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addContainerGap())
						.addComponent(pnlButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(pnlLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
		if (saveConfig()) {
			close();
		}
	}//GEN-LAST:event_btnOKActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		close();
	}//GEN-LAST:event_btnCancelActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		close();
	}//GEN-LAST:event_formWindowClosing

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnOK;
	private javax.swing.JLabel lblServerURL;
	private javax.swing.JPanel pnlButton;
	private javax.swing.JPanel pnlLocal;
	private javax.swing.JTextField txtServerURL;
	// End of variables declaration//GEN-END:variables
}
