package org.javlo.client.localmodule.ui;

import java.awt.Component;
import java.awt.Dialog;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

import org.javlo.client.localmodule.model.ServerConfig;
import org.javlo.client.localmodule.model.ServerType;
import org.javlo.client.localmodule.service.ConfigService;
import org.javlo.client.localmodule.service.I18nService;
import org.javlo.helper.StringHelper;

/**
 *
 * @author lg2dc
 */
public class ServerFrame extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

	private static ServerFrame instance;

	public static void showDialog(ConfigFrame parent, ServerConfig server) {
		synchronized (ServerFrame.class) {
			if (instance == null) {
				instance = new ServerFrame();
				instance.loadConfig(parent, server);
				instance.setLocationRelativeTo(parent);
				instance.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
				instance.setVisible(true);
			} else {
				instance.toFront();
			}
		}
	}

	private I18nService i18n = I18nService.getInstance();

	private ServerConfig serverConfig;
	private ConfigFrame parent;

	public ServerFrame() {
		initComponents();
		getRootPane().setDefaultButton(btnOK);
		cmbType.setModel(new DefaultComboBoxModel(ServerType.values()));
		cmbType.setRenderer(new DefaultListCellRenderer() {
			@Override
			public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
				Component out = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
				if (value instanceof ServerType && out instanceof JLabel) {
					ServerType serverType = (ServerType) value;
					((JLabel) out).setText(i18n.get("config.server.type." + serverType.name().toLowerCase()));
				}
				return out;
			}
		});
		refreshUIState();
	}

	public void close() {
		synchronized (ServerFrame.class) {
			this.setVisible(false);
			this.dispose();
			instance = null;
		}
	}

	private void refreshUIState() {
		pnlSiteMonitor.setEnabled(ServerType.OTHER.equals(cmbType.getSelectedItem()));
	}

	private void loadConfig(ConfigFrame parent, ServerConfig server) {
		this.parent = parent;
		this.serverConfig = server;
		txtServerURL.setText(server.getServerURL());
		txtTitle.setText(server.getTitle());
		cmbType.setSelectedItem(server.getType());
		txtCheckPhrase.setText(server.getCheckPhrase());
		refreshUIState();
	}

	private boolean saveConfig() {
		//Parse an check input values
		String serverURL = StringHelper.trimAndNullify(txtServerURL.getText());
		if (!ConfigService.checkServerURL(serverURL)) {
			JOptionPane.showMessageDialog(this, i18n.get("error.invalid-server-url"), i18n.get("error"), JOptionPane.ERROR_MESSAGE);
			txtServerURL.requestFocus();
			return false;
		}
		String title = txtTitle.getText();
		ServerType type = (ServerType) cmbType.getSelectedItem();
		String checkPhrase = txtCheckPhrase.getText();

		//Store
		serverConfig.setServerURL(serverURL);
		serverConfig.setTitle(title);
		serverConfig.setType(type);
		serverConfig.setCheckPhrase(checkPhrase);
		parent.onServerUpdate(serverConfig);
		return true;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLocal = new javax.swing.JPanel();
        txtServerURL = new javax.swing.JTextField();
        lblServerURL = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        btnTitleAuto = new javax.swing.JButton();
        pnlSiteMonitor = new javax.swing.JPanel();
        txtCheckPhrase = new javax.swing.JTextField();
        lblCheckPhrase = new javax.swing.JLabel();
        pnlButton = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(i18n.get("config.server-title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblServerURL.setText(i18n.get("config.server.url")); // NOI18N

        lblTitle.setText(i18n.get("config.server.title")); // NOI18N

        lblType.setText(i18n.get("config.server.type")); // NOI18N

        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        btnTitleAuto.setText(i18n.get("config.server.action.auto-title")); // NOI18N
        btnTitleAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitleAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLocalLayout = new javax.swing.GroupLayout(pnlLocal);
        pnlLocal.setLayout(pnlLocalLayout);
        pnlLocalLayout.setHorizontalGroup(
            pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalLayout.createSequentialGroup()
                .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblType)
                    .addComponent(lblServerURL)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocalLayout.createSequentialGroup()
                        .addComponent(txtServerURL)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocalLayout.createSequentialGroup()
                        .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTitleAuto)
                        .addGap(137, 137, 137))))
        );
        pnlLocalLayout.setVerticalGroup(
            pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLocalLayout.createSequentialGroup()
                .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServerURL)
                    .addComponent(txtServerURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitleAuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblType)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlSiteMonitor.setBorder(javax.swing.BorderFactory.createTitledBorder(i18n.get("config.server.site-monitor-config"))); // NOI18N

        lblCheckPhrase.setText(i18n.get("config.server.checkphrase")); // NOI18N

        javax.swing.GroupLayout pnlSiteMonitorLayout = new javax.swing.GroupLayout(pnlSiteMonitor);
        pnlSiteMonitor.setLayout(pnlSiteMonitorLayout);
        pnlSiteMonitorLayout.setHorizontalGroup(
            pnlSiteMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSiteMonitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCheckPhrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCheckPhrase)
                .addContainerGap())
        );
        pnlSiteMonitorLayout.setVerticalGroup(
            pnlSiteMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSiteMonitorLayout.createSequentialGroup()
                .addGroup(pnlSiteMonitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckPhrase)
                    .addComponent(txtCheckPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnOK.setText(i18n.get("dialog.ok")); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText(i18n.get("dialog.cancel")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSiteMonitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSiteMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
		if (saveConfig()) {
			close();
		}
	}//GEN-LAST:event_btnOKActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		close();
	}//GEN-LAST:event_btnCancelActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		close();
	}//GEN-LAST:event_formWindowClosing

	private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
		refreshUIState();
	}//GEN-LAST:event_cmbTypeActionPerformed

	private void btnTitleAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitleAutoActionPerformed
		String title = ServerConfig.getLabelFromUrl(txtServerURL.getText());
		if (title == null) {
			JOptionPane.showMessageDialog(this,
					i18n.get("config.server.error.auto-title-failed.message"),
					i18n.get("config.server.error.auto-title-failed.title"),
					JOptionPane.ERROR_MESSAGE);
		} else {
			txtTitle.setText(title);
		}
	}//GEN-LAST:event_btnTitleAutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnTitleAuto;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel lblCheckPhrase;
    private javax.swing.JLabel lblServerURL;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlLocal;
    private javax.swing.JPanel pnlSiteMonitor;
    private javax.swing.JTextField txtCheckPhrase;
    private javax.swing.JTextField txtServerURL;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
